### ISSUE TITLE
mutt-ical.py / python3 issue

### ISSUE THREAD

**Issue by gfumaroli** [marvinthepa/mutt-ical#10]
When running the script with Python3, you get the following error:
Traceback (most recent call last):
  File "/home/guf/guf/scripts//mutt-ical.py", line 206, in <module>
    execute(mutt_command, mailtext)
  File "/home/guf/guf/scripts//mutt-ical.py", line 97, in execute
    process.stdin.write(mailtext)
TypeError: a bytes-like object is required, not 'str'

This can be avoided by replacing "process.stdin.write(mailtext)" by "process.stdin.write(mailtext.encode())" at line 97.

**Comment by marvinthepa** [comment]
As you so accurately describe the solution, do want to create a pull request?

**Comment by gfumaroli** [comment]
Thank you for your proposal and this project overall. But as I just started to use mutt-ical yesterday, I cannot really tell if the script still works as intended with the fix I proposed. I am sure you are in better position to confirm there is no regression.

**Comment by marvinthepa** [comment]
@gfumaroli your suggestion seems right to me, I think you should gather the courage to submit a pull request so your contribution is visible.

As written earlier, I am just the guy clicking the "merge" button, I do not do any testing of this script either. I currently do not use it myself.

**Comment by penguineer** [comment]
This might have been fixed, as the call is now `execute(sendmail() + ['--', to], message.as_bytes())` in line 220.
