### ISSUE TITLE
The meeting start and end is not displayed

### ISSUE THREAD

**Issue by MEschenbacher** [marvinthepa/mutt-ical#3]
I'm receiving Microsoft meeting invitations for which the this script does not output essential information. Is there a way to configure which information is displayed?

**Comment by marvinthepa** [comment]
I am not personally using mutt-ical anymore. I had a quick glance and the source and adding what you want should be straightforward. Check out the `display` function and play a bit with the http://eventable.github.io/vobject/ package to find out how to access the additional information that you want to display.

Pull requests are accepted if you want to share your code.

**Comment by C-Otto** [comment]
```
20a21,22
> from tzlocal import get_localzone
138a139,140
>     start = str(ical.vevent.dtstart.value.astimezone(get_localzone()))
>     end = str(ical.vevent.dtend.value.astimezone(get_localzone()))
150a153,155
>     sys.stdout.write("Start:\t" + start + "\n")
>     sys.stdout.write("End:\t" + end + "\n")
>     sys.stdout.write("\n")
```

**Comment by marvinthepa** [comment]
@C-Otto:

> Pull requests are accepted...

**Comment by C-Otto** [comment]
I know.
