### ISSUE TITLE
dict object has no attribute 'has_key' error

### ISSUE THREAD

**Issue by romariolopezc** [marvinthepa/mutt-ical#6]
Hello, I have an issue when trying to use this

```
Traceback (most recent call last):
  File "/home/rlopez/.config/neomutt/mutt-ical.py", line 165, in <module>
    display(invitation)
  File "/home/rlopez/.config/neomutt/mutt-ical.py", line 121, in display
    if ical.vevent.contents.has_key('organizer'):
AttributeError: 'dict' object has no attribute 'has_key'
Press any key to continue...```

Let me know how I can help

**Comment by marvinthepa** [comment]
What python version are you using where a `dict` does not have `has_key`?

**Comment by vikasrawal** [comment]
I have the same problem on Python 3.9.1

**Comment by marvinthepa** [comment]
closed by #7

**Comment by vikasrawal** [comment]
I now get this error:

KeyError: 'X-NUM-GUESTS'

If I remove X-NUM-GUESTS from like 37, I get 

KeyError: 'CUTYPE'

And I remove CUTYPE also, I get this error:

TypeError: a bytes-like object is required, not 'str'
Press any key to continue...Refusing to send an empty email
Try: echo | neomutt -s 'subject' user@example.com

In the end, I am still unable to use this.

**Comment by marvinthepa** [comment]
last comment was also copied to #8
