### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by vikasrawal** [marvinthepa/mutt-ical#8]
After the latest update, I now get this error:

KeyError: 'X-NUM-GUESTS'

If I remove X-NUM-GUESTS from line 37, I get

KeyError: 'CUTYPE'

And I remove CUTYPE also, I get this error:

TypeError: a bytes-like object is required, not 'str'
Press any key to continue...Refusing to send an empty email
Try: echo | neomutt -s 'subject' user@example.com

In the end, I am still unable to use this.

**Comment by marvinthepa** [comment]
> After the latest update, I now get this error:

Have you thought about contacting the author of this update? Maybe they will be able to help.
I am just the guy who clicks the "merge" button ;-).

Seriously, this is a tiny script that I wrote ages ago (for python 2) that I just put on github in case someone else wants to use it.
If it does not work for you (on python 3), feel free to fix it.

**Comment by vikasrawal** [comment]
I did the minor update. But that only fixes one problem, while there are obviously more.

**Comment by marvinthepa** [comment]
Okay, as some of the errors above are fixed (and I do not no which) I will close this now.

@vikasrawal you can open a new issue with the remaining errors, but please do not expect anybody working on it (see above).
Pull requests still accepted, of course.
